Log errors in color yellow
MarshallOfSound/OpenLog pull request #7
Opened 2017-07-19 14:14 UTC by Ra1da35ma

- Added a few more colors 
- log `console.error()` in _yellow_

2017-07-20 04:31 UTC, MarshallOfSound commented on server/server.js
> +		red: ['\x1b[31m', '\x1b[0m'],
Purely from a pedantic perspective but it looks like the indenting here is a bit off, can you fix that and then I can merge 😄

2017-07-20 04:31 UTC, MarshallOfSound requested changes
See comment

2017-07-28 10:19 UTC, Ra1da35ma commented on server/server.js
> +		red: ['\x1b[31m', '\x1b[0m'],
oh cool... I live on that perspective too
will fix

2017-07-28 10:22 UTC, radiumrasheed reviewed
indentation fixed

2017-07-28 10:24 UTC, MarshallOfSound approved these changes

2017-07-28 10:24 UTC, merged